### ISSUE TITLE
Might be a problem with Activities when editing existing files

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#207]
It appears that if you try to overwrite an existing design that it does not overwrite the Activities, so you get errors about non-unique URIs.  I've seen this with iGEM parts and the igem2sbol Activity.

**Comment by michael13162** [comment]
I'm having a problem with createCopy.  I'm copying http://michael.zhang/UnnamedPart_SBOLDesignerActivity/1 from doc into design.  Before the call, design doesn't have the activity, and doc does.  The documentation doesn't mention why it could fail.  Do you have any insights?

java.lang.IllegalArgumentException: Unable to copy http://michael.zhang/UnnamedPart_SBOLDesignerActivity/1
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1338)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1169)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1145)
	at edu.utah.ece.async.sboldesigner.sbol.SBOLUtils.insertTopLevels(SBOLUtils.java:472)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel.saveIntoExistingFile(SBOLDesignerPanel.java:535)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel.save(SBOLDesignerPanel.java:455)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLDesignerPanel$6.perform(SBOLDesignerPanel.java:159)
	at edu.utah.ece.async.sboldesigner.sbol.editor.SBOLEditorAction.actionPerformed(SBOLEditorAction.java:91)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
This was a bug in libSBOLj (see #505).  Should be fixed now.  Please test.

**Comment by michael13162** [comment]
I tested it and there are still problems.  Namely, none of the activities are showing up linked after I save in SBOLDesigner.  I debugged it, and I thought at first the problem might be with createRecursiveCopy.  But no, it's actually still createCopy.  I don't think createCopy is copying over wasGeneratedBy fields.  

design.createCopy(doc);

doc has a CD with wasGeneratedBy Activity.  After this line, design has the Activity, but all CDs now don't refer to it via wasGeneratedBy.  This was tricky to figure out because SBOLDesigner is copying things all over the place when saving.

**Comment by cjmyers** [comment]
Yes, this was another oversight.  I think I’ve just checked in a fix.  Please test.

**Comment by michael13162** [comment]
Tried again, and still isn't working.  Is createRecursiveCopy copying Activities?  Is createCopy copying an Activity's associations?

**Comment by cjmyers** [comment]
Good catches.  These were indeed all missed.  I think I’ve fixed them.  Please test again.

**Comment by michael13162** [comment]
I just tried again, and the Association on the Activity still doesn't seem to be copied (either in createCopy or createRecursiveCopy).

**Comment by michael13162** [comment]
I looked into it more:

createRecursiveCopy is not copying Activities (you copy into "this", but maybe you want to copy into the doc you return and not the doc that was called on?)

createCopy is not copying Associations of Activities

**Comment by cjmyers** [comment]
I’m not seeing it.  Which line are your referring to?

**Comment by michael13162** [comment]
Everything worked after I pulled.....................................................

Sorry for the confusion.  I'm closing this issue now because I don't see anything else wrong.  Activities and their creators, timestamps, and Associations are now all present.
